apiVersion: v1
kind: Service
metadata:
  name: {{ include "fortio.fullname" . }}
  labels:
    {{- include "fortio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- with .Values.service.ports }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  selector:
    {{- include "fortio.selectorLabels" . | nindent 4 }}
