image:
  repository: fortio/fortio
  pullPolicy: IfNotPresent

  # Defaults to appVersion in Chart.yaml
  tag: ""

podAnnotations: {}

service:
  ports:
    # UI / Rest API / HTTP echo service
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    # GRPC ping service
    - port: 8079
      targetPort: 8079
      protocol: TCP
      name: grpc
      
  type: ClusterIP
  port: 80


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Constrain pod to run on a select set of nodes
nodeSelector: {}

# Tolerations are applied to pods, and allow (but do not require) the pods to schedule onto nodes with matching taints.
tolerations: []

# Node affinity is a property of Pods that attracts them to a set of nodes (either as a preference or a hard requirement). 
affinity: {}
